### ISSUE TITLE
Gradient not working

### ISSUE THREAD

**Issue by HnryStGTkr** [pizza-plz/safe-info#2]

**Comment by pizza-plz** [comment]
https://forum.arduino.cc/index.php?topic=288104.0

**Comment by HnryStGTkr** [comment]
That's using a different method though. Ours uses R string literal: https://www.geeksforgeeks.org/raw-string-literal-c/
Can you save the code that is output by the device (or inspect it)? Want to see if the R string literal messed up the gradient declaration line

**Comment by HnryStGTkr** [comment]
i'll do some more commits with different types of gradients you can try out in a bit

**Comment by pizza-plz** [comment]
http://75.33.78.25/

**Comment by HnryStGTkr** [comment]
YEP. gradient line is not even present. The parens throw it off maybe.

**Comment by pizza-plz** [comment]
hey bro, you gonna be around at all tonight?

**Comment by HnryStGTkr** [comment]
Yea I'll be around

**Comment by pizza-plz** [comment]
gonna pull that code in, just woke back up

**Comment by pizza-plz** [comment]
first pr didnt work, trying the 2nd

**Comment by HnryStGTkr** [comment]
make sure that style.css file is in the right place...and the localhost URL in the ino file is right

**Comment by HnryStGTkr** [comment]
we could even point it to the github file if we had to...ha

**Comment by pizza-plz** [comment]
lets try that... its not wanting to do the local version probably because of the way its hosted

**Comment by pizza-plz** [comment]
i got it working, hosted it using gitCDN
the issue was the MIME type stuff not working when using just the raw file.  committing the change now

**Comment by HnryStGTkr** [comment]
oh ok. nice!

**Comment by pizza-plz** [comment]
any ideas for the weather stuff?

**Comment by HnryStGTkr** [comment]
Visually yea.. not sure how you want to retrieve the data. Will you parse json in c++ , or? We might just be able to do it in javascript in the html page.
I was looking at climacell.co - seems decent.
DarkSky that I mentioned before is closed down now.

**Comment by pizza-plz** [comment]
i will be fine with javascript if thats what you think will work

**Comment by HnryStGTkr** [comment]
Yea, probably is the easiest route and will still keep data and presentation somewhat divided.
Separately, I've been learning to parse JSON in good ol C99 right now, it's been difficult, and I've never touched C++ so it's probably not gonna happen from me unless it's javascript. Can write CSS all day so i'll just play to my strengths here, get the climacell started, then if i run into anything i'll let you finish that.
